{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7705dbb5-47bc-44f2-87cb-7ccd9deb2fb3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "from tkinter.scrolledtext import ScrolledText\n",
    "\n",
    "class Kurs:\n",
    "    def __init__(self, kurs_adi, egitmen, icerik):\n",
    "        self.kurs_adi = kurs_adi\n",
    "        self.egitmen = egitmen\n",
    "        self.icerik = icerik\n",
    "\n",
    "class Egitmen:\n",
    "    def __init__(self, isim, uzmanlik):\n",
    "        self.isim = isim\n",
    "        self.uzmanlik = uzmanlik\n",
    "\n",
    "class Ogrenci:\n",
    "    def __init__(self, isim, email, sifre, secilen_ogretmen):\n",
    "        self.isim = isim\n",
    "        self.email = email\n",
    "        self.sifre = sifre\n",
    "        self.secilen_ogretmen = secilen_ogretmen\n",
    "\n",
    "class Uygulama:\n",
    "    def __init__(self, pencere):\n",
    "        self.pencere = pencere\n",
    "        self.pencere.title(\"Online Eğitim Platformu\")\n",
    "\n",
    "        self.kayitli_ogrenciler = []  \n",
    "        self.kurslar = {\n",
    "            \"Ümit Özdağ - Milli Güvenlik\": Kurs(\"Ümit Özdağ - Milli Güvenlik\", \"Ümit Özdağ\", \n",
    "                                                 \"Milli güvenlik, ulus milletin, vatan topraklarının, deniz kıta sahanlığının, millî kurumlar, değerler ve çıkarların tüm askeri, siyasi, diplomatik ve ekonomik imkânlar kullanılarak iç ve dış tehditlerden korunumunu ifade eden genel bir topyekûn savunma ve tehdit önleme kavramıdır. Kararlı ve istikrarlı bir anayurt güvenliği sağlanabilmesi için birçok ülke tarafından uygulanan genel stratejiler arasında.\"),\n",
    "            \"Efloud - Price Action\": Kurs(\"Efloud - Price Action\", \"Efloud\", \n",
    "                                           \"Price Action Stratejisi Nedir, Nasıl Uygulanır?\\n\\n\"\n",
    "                                           \"Price Action stratejisi, karmaşık göstergeler veya osilatörler kullanmadan sadece fiyat grafiğini inceleyerek uygulanır. \"\n",
    "                                           \"Price Action stratejisinin uygulanmasında şu adımlar takip edilir:\\n\\n\"\n",
    "                                           \"- Destek ve Direnç Seviyelerini Belirleme: Bu seviyeler, fiyatın tarihsel olarak zorlandığı veya geri çekildiği bölgelerdir. Yatırımcılar, bu seviyelere yaklaştığında fiyatın tepki vereceğini beklerler.\\n\"\n",
    "                                           \"- Trendin Belirlenmesi: Price Action yatırımcıları genellikle ‘trend dostunuzdur’ ilkesini benimserler. Fiyat hareketinin genel yönü belirlenir ve ticaret bu yöne doğru yapılır.\\n\"\n",
    "                                           \"- Fiyat Formasyonlarını ve Modellerini Tanıma: Fiyat hareketleri içinde belirginleşen bazı formasyonlar (örneğin, çift tepe, çift dip, bayrak ve flama formasyonları) gelecekteki hareketleri tahmin etmek için kullanılır.\\n\"\n",
    "                                           \"- Giriş ve Çıkış Noktalarını Belirleme: Destek, direnç ve fiyat formasyonlarına dayanarak, ticarete ne zaman girilip çıkılacağına karar verilir.\\n\"\n",
    "                                           \"- Risk Yönetimi ve Pozisyon Boyutlandırma: Her ticarette, ne kadar risk alınacağını ve pozisyon boyutunun ne olacağını belirlemek kritiktir. \"\n",
    "                                           \"Price Action stratejisi uygularken, potansiyel zararın sınırlanması için durdurma emirleri (stop-loss) sıklıkla kullanılır.\\n\\n\"\n",
    "                                           \"Price Action stratejisi, tecrübe ve pratik gerektiren bir yaklaşımdır. Başarılı olabilmek için, yatırımcının piyasa hareketlerini dikkatlice gözlemleyerek ve analiz ederek sürekli olarak öğrenmesi ve kendini geliştirmesi gerekir.\"),\n",
    "            \"Marcus Aurelius - Felsefe\": Kurs(\"Marcus Aurelius - Felsefe\", \"Marcus Aurelius\", \n",
    "                                              \"Genellikle “Filozof Kral” olarak anılan Marcus Aurelius, M.S. 2. yüzyılda Roma İmparatorluğu’nu yönetiyordu. \"\n",
    "                                              \"Ancak mirası siyasi başarılarının çok ötesine uzanıyor. Marcus Aurelius’u gerçekten istisnai kılan şey, insan deneyimine dair derin anlayışı ve yazıları aracılığıyla ebedi bilgeliği aktarma yeteneğidir. \"\n",
    "                                              \"Şimdi işimize bakalım. Neden Marcus Aurelius konusunda bu kadar heyecanlıyım?\\n\\n\"\n",
    "                                              \"Her şey onun “Meditasyonlar” olarak bilinen hayranlık uyandıran düşünce ve yansıma koleksiyonuna indirgeniyor. Bilge bir imparatorun ruhunu döktüğü ve hayata, mutluluğa ve insan varoluşumuzun özüne dair samimi düşüncelerini paylaştığı gizli bir bilgelik hazinesine rastladığınızı hayal edin.\\n\\n\"\n",
    "                                              \"Bu mücevheri ilk keşfettiğimde hayatımı bu kadar derinden etkileyeceğine dair hiçbir fikrim yoktu. Ama şunu söyleyeyim, internetin uçsuz bucaksız çölünde gizli bir vahaya rastlamak gibiydi. \"\n",
    "                                              \"Marcus Aurelius’un Stoacı felsefesi varlığımın derinliklerinde bir etki yarattı.\")\n",
    "        }\n",
    "\n",
    "        self.isim_etiket = tk.Label(pencere, text=\"İsim:\", font=(\"Arial\", 12))\n",
    "        self.isim_etiket.grid(row=0, column=0)\n",
    "\n",
    "        self.isim_giris = tk.Entry(pencere, font=(\"Arial\", 12))\n",
    "        self.isim_giris.grid(row=0, column=1)\n",
    "\n",
    "        self.eposta_etiket = tk.Label(pencere, text=\"E-posta:\", font=(\"Arial\", 12))\n",
    "        self.eposta_etiket.grid(row=1, column=0)\n",
    "\n",
    "        self.eposta_giris = tk.Entry(pencere, font=(\"Arial\", 12))\n",
    "        self.eposta_giris.grid(row=1, column=1)\n",
    "\n",
    "        self.sifre_etiket = tk.Label(pencere, text=\"Şifre:\", font=(\"Arial\", 12))\n",
    "        self.sifre_etiket.grid(row=2, column=0)\n",
    "\n",
    "        self.sifre_giris = tk.Entry(pencere, show=\"*\", font=(\"Arial\", 12))\n",
    "        self.sifre_giris.grid(row=2, column=1)\n",
    "\n",
    "        self.ogretmenler = [\"Ümit Özdağ - Milli Güvenlik\", \"Efloud - Price Action\", \"Marcus Aurelius - Felsefe\"]\n",
    "        self.secilen_ogretmen = tk.StringVar(pencere)\n",
    "        self.secilen_ogretmen.set(self.ogretmenler[0]) \n",
    "\n",
    "        self.ogretmen_etiket = tk.Label(pencere, text=\"Öğretmen ve Ders Seçimi:\", font=(\"Arial\", 12))\n",
    "        self.ogretmen_etiket.grid(row=3, column=0)\n",
    "\n",
    "        self.ogretmen_secim = tk.OptionMenu(pencere, self.secilen_ogretmen, *self.ogretmenler)\n",
    "        self.ogretmen_secim.grid(row=3, column=1)\n",
    "\n",
    "        self.giris_buton = tk.Button(pencere, text=\"Giriş Yap\", command=self.giris_yap, font=(\"Arial\", 12))\n",
    "        self.giris_buton.grid(row=4, column=0)\n",
    "\n",
    "        self.kayit_ol_buton = tk.Button(pencere, text=\"Kayıt Ol\", command=self.kayit_ol, font=(\"Arial\", 12))\n",
    "        self.kayit_ol_buton.grid(row=4, column=1)\n",
    "\n",
    "    def giris_yap(self):\n",
    "        eposta = self.eposta_giris.get()\n",
    "        sifre = self.sifre_giris.get()\n",
    "\n",
    "        for ogrenci in self.kayitli_ogrenciler:\n",
    "            if ogrenci.email == eposta and ogrenci.sifre == sifre:\n",
    "                self.giris_yapildi(ogrenci)\n",
    "                return\n",
    "\n",
    "        messagebox.showerror(\"Hata\", \"E-posta veya şifre hatalı!\")\n",
    "\n",
    "    def kayit_ol(self):\n",
    "        isim = self.isim_giris.get()\n",
    "        eposta = self.eposta_giris.get()\n",
    "        sifre = self.sifre_giris.get()\n",
    "        secilen_ogretmen = self.secilen_ogretmen.get()\n",
    "\n",
    "        for ogrenci in self.kayitli_ogrenciler:\n",
    "            if ogrenci.email == eposta:\n",
    "                messagebox.showerror(\"Hata\", \"Bu e-posta adresiyle daha önce kayıt yapılmış!\")\n",
    "                return\n",
    "\n",
    "        self.kayitli_ogrenciler.append(Ogrenci(isim, eposta, sifre, secilen_ogretmen))\n",
    "        messagebox.showinfo(\"Başarılı\", \"Kayıt işlemi başarılı!\")\n",
    "\n",
    "    def giris_yapildi(self, ogrenci):\n",
    "        messagebox.showinfo(\"Hoş Geldiniz\", f\"Hoş geldiniz, {ogrenci.isim}!\")\n",
    "\n",
    "        ders_icerik = self.kurslar[ogrenci.secilen_ogretmen].icerik\n",
    "        self.ders_icerik_penceresi = tk.Toplevel(self.pencere)\n",
    "        self.ders_icerik_penceresi.title(\"Ders İçeriği\")\n",
    "\n",
    "        ders_icerik_text = ScrolledText(self.ders_icerik_penceresi, width=60, height=20, font=(\"Arial\", 12))\n",
    "        ders_icerik_text.insert(tk.END, ders_icerik)\n",
    "        ders_icerik_text.pack()\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    pencere = tk.Tk()\n",
    "    uygulama = Uygulama(pencere)\n",
    "    pencere.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac157741-f196-44a0-bd02-7a09403276b1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
